architecture:
  name: "AMOEBA_4x4_CGRA_2x2_Tiles"
  version: "1.0"

multi_cgra_defaults:
  base_topology: "mesh"
  rows: 4
  columns: 4

per_cgra_defaults:
  rows: 2
  columns: 2
  ctrl_mem_items: 20
  context_mem_items: 6
  base_topology: "mesh"

tile_defaults:
  num_registers: 32
  fu_types: ["add", "mul", "div", "fadd", "fmul", "fdiv", "logic", "cmp", "sel", "type_conv", "vfmul", "fadd_fadd", "fmul_fadd", "grant", "loop_control", "phi", "constant", "mem", "return", "mem_indexed", "alloca", "shift", "counter", "extract_predicate"]

link_defaults:
  latency: 1
  bandwidth: 32

link_overrides:

tile_overrides:
